-- Since SQLite doesn't support complex ALTER TABLE easily, the safest down migration for the index-only changes is to drop the new indexes and recreate the old ones.

DROP INDEX IF EXISTS `idx_media_message_id`;
DROP INDEX IF EXISTS `idx_media_uploaded_by`;
DROP INDEX IF EXISTS `idx_media_pending_upload`;
DROP INDEX IF EXISTS `idx_media_hash`;
DROP INDEX IF EXISTS `idx_ann_comments_created`;
DROP INDEX IF EXISTS `idx_announcements_active_created`;
DROP INDEX IF EXISTS `idx_audit_action_created`;
DROP INDEX IF EXISTS `idx_conversations_unread_last`;
DROP INDEX IF EXISTS `idx_dm_reactions_message`;
DROP INDEX IF EXISTS `uq_dm_reaction`;
DROP INDEX IF EXISTS `idx_dm_thread_fwd`;
DROP INDEX IF EXISTS `idx_dm_thread_rev`;
DROP INDEX IF EXISTS `idx_dm_recipient_created`;
DROP INDEX IF EXISTS `idx_internal_reactions_message`;
DROP INDEX IF EXISTS `uq_internal_reaction`;
DROP INDEX IF EXISTS `idx_internal_messages_created`;
DROP INDEX IF EXISTS `idx_message_reactions_message`;
DROP INDEX IF EXISTS `uq_message_reaction`;
DROP INDEX IF EXISTS `idx_messages_conv_created`;
DROP INDEX IF EXISTS `idx_messages_conv_unread`;
DROP INDEX IF EXISTS `idx_messages_sender_created`;
DROP INDEX IF EXISTS `idx_password_reset_user_expires`;
DROP INDEX IF EXISTS `idx_refresh_active`;
DROP INDEX IF EXISTS `idx_sessions_user_active`;
DROP INDEX IF EXISTS `idx_users_role_created`;

CREATE INDEX `idx_ann_comments_announcement` ON `announcement_comments` (`announcement_id`,`created_at`);
CREATE INDEX `idx_ann_comments_user` ON `announcement_comments` (`user_id`);
CREATE INDEX `idx_ann_reactions_user` ON `announcement_reactions` (`user_id`);
CREATE INDEX `idx_announcement_votes_user` ON `announcement_votes` (`user_id`);
CREATE INDEX `idx_announcements_active` ON `announcements` (`is_active`,`created_at`);
CREATE INDEX `idx_audit_action` ON `audit_logs` (`action`);
CREATE INDEX `idx_audit_entity` ON `audit_logs` (`entity_type`,`entity_id`);
CREATE INDEX `idx_audit_created` ON `audit_logs` (`created_at`);
CREATE INDEX `idx_conversations_user_id` ON `conversations` (`user_id`);
CREATE INDEX `idx_conversations_unread` ON `conversations` (`unread_count`);
CREATE INDEX `idx_conversations_unread_last` ON `conversations` (`unread_count`,`last_message_at`);
CREATE INDEX `idx_dm_reactions_user` ON `direct_message_reactions` (`user_id`);
CREATE UNIQUE INDEX `uq_dm_reaction` ON `direct_message_reactions` (`message_id`,`user_id`,`emoji`);
CREATE INDEX `idx_dm_sender` ON `direct_messages` (`sender_id`);
CREATE INDEX `idx_dm_recipient` ON `direct_messages` (`recipient_id`);
CREATE INDEX `idx_dm_thread` ON `direct_messages` (`sender_id`,`recipient_id`,`created_at`);
CREATE INDEX `idx_dm_created` ON `direct_messages` (`created_at`);
CREATE INDEX `idx_internal_reactions_user` ON `internal_message_reactions` (`user_id`);
CREATE UNIQUE INDEX `uq_internal_reaction` ON `internal_message_reactions` (`message_id`,`user_id`,`emoji`);
CREATE INDEX `idx_internal_messages_sender` ON `internal_messages` (`sender_id`);
CREATE INDEX `idx_internal_messages_created` ON `internal_messages` (`created_at`);
CREATE INDEX `idx_message_reactions_user` ON `message_reactions` (`user_id`);
CREATE UNIQUE INDEX `uq_message_reaction` ON `message_reactions` (`message_id`,`user_id`,`emoji`);
CREATE INDEX `idx_messages_conversation_created` ON `messages` (`conversation_id`,`created_at`);
CREATE INDEX `idx_messages_conversation_status` ON `messages` (`conversation_id`,`status`);
CREATE INDEX `idx_messages_sender` ON `messages` (`sender_id`);
CREATE INDEX `idx_messages_deleted` ON `messages` (`deleted_at`);
CREATE INDEX `idx_messages_conv_del_created` ON `messages` (`conversation_id`,`deleted_at`,`created_at`);
CREATE INDEX `idx_password_reset_user_id` ON `password_reset_tokens` (`user_id`);
CREATE INDEX `idx_password_reset_expires` ON `password_reset_tokens` (`expires_at`);
CREATE INDEX `idx_password_reset_used_at` ON `password_reset_tokens` (`used_at`);
CREATE INDEX `idx_refresh_user` ON `refresh_tokens` (`user_id`);
CREATE INDEX `idx_refresh_active` ON `refresh_tokens` (`user_id`,`revoked_at`);
CREATE INDEX `idx_sessions_user_id` ON `sessions` (`user_id`);
CREATE INDEX `idx_sessions_user_active` ON `sessions` (`user_id`,`revoked_at`);
CREATE INDEX `idx_users_email` ON `users` (`email`);
CREATE INDEX `idx_users_status` ON `users` (`status`);
CREATE INDEX `idx_users_role` ON `users` (`role`);
